# LLM Configuration
llm:
  provider: "openai"
  model_name: "gpt-5.1"
  top_p: 1.00
  temperature: 0.25
  reasoning: "high"    # options: "none | low | medium | high"
  text: "low"    # output verbosity; options: "low | medium | high"
  max_tokens: -1
  prompt_file: "prompt_5"

embedding_model:
  provider: "openai"
  model_name: "text-embedding-3-large"

eval_model:
  provider: "openai"
  model_name: "gpt-5.1"
  reasoning: "high"

# File Paths
paths:
  prompts_dir: "prompts"
  interview_data_dir: "data"
  test_questions_file: "data/test_questions_answers.xlsx"
  output_dir: "outputs"

# MLflow Configuration
mlflow:
  experiment_name: "PoC_test9_h_l_pr_5_epr_2"
  mlruns: "sqlite:///mlflow.db"


